### ISSUE TITLE
Blockchain Explorer not working

### ISSUE THREAD

**Issue by scottpgallagher** [yeasy/docker-compose-files#102]
When I utilize this repository the blockchain explorer isn't connecting correctly:

$ sudo docker logs confident_poitras
Compiling all doT templates...
Compiling HyperlegerExplorer.jst to file
{ Error: connect ECONNREFUSED 127.0.0.1:7050
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7050 }

and it's listening on port 7050:
$ telnet localhost 7050
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

I've also tried running the explorer by itself:

$ sudo docker run -p 9090:9090 -e HYP_REST_ENDPOINT=http://127.0.0.1:7050 yeasy/blockchain-explorer
Compiling all doT templates...
Compiling HyperlegerExplorer.jst to file
{ Error: connect ECONNREFUSED 127.0.0.1:7050
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7050 }

Does the orderer have some kind of file that is preventing this that needs changed prior to doing the make start command?

**Comment by scottpgallagher** [comment]
If I use the IP address tied to my docker0 network address:

$ sudo docker run -p 9090:9090 -e HYP_REST_ENDPOINT=http://172.17.0.1:7050 --network=103_default yeasy/blockchain-explorer
Compiling all doT templates...
Compiling HyperlegerExplorer.jst to file
{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }

**Comment by scottpgallagher** [comment]
I believe this is due to the 1.0.3 version enabling TLS and the blockchain-explorer not set to use it (by default).

**Comment by yeasy** [comment]
Pls file an issue at yeasy/blockchain-explorer project if you believe it's related to that.
