### ISSUE TITLE
Error(s) with docker compose hyperledger 1.0

### ISSUE THREAD

**Issue by bonen** [yeasy/docker-compose-files#13]
Hi yeasy,

Thanks a lot for all the great docker images you are providing, very helpfull!
I ran into problems though running the docker-compose file for hyperledger 1.0.
https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/docker-compose.yml

**Errors I get for fabric-vp0**
2017-02-06 14:21:16.171 UTC [peer/gossip/sa] OrgByPeerIdentity -> ERRO 124 Invalid Peer Identity. It must be different from nil.
2017-02-06 14:21:16.171 UTC [peer/gossip/mcs] GetPKIidOfCert -> ERRO 126 Invalid Peer Identity. It must be different from nil.
2017-02-06 14:21:19.175 UTC [deliveryClient] NewDeliverService -> ERRO 132 Cannot dial to orderer:7050, because of grpc: timed out when dialing

**Warnings I get for fabric-vp0**
2017-02-06 14:29:37.728 UTC [inproccontroller] getInstance -> WARN 072 chaincode instance exists for cscc-1.0.0-snapshot-preview
2017-02-06 14:29:37.808 UTC [channelState-172.18.0.3:7051] ConfigureChannel -> WARN 125 Cannot extract org identity from certificate, aborting.
2017-02-06 14:29:37.808 UTC [discovery-172.18.0.3:7051] Connect -> WARN 127 Empty PkiID, aborting
2017-02-06 14:29:40.814 UTC [gossipService] InitializeChannel -> WARN 133 Cannot create delivery client, due to grpc: timed out when dialing
2017-02-06 14:29:40.814 UTC [gossipService] InitializeChannel -> WARN 134 Delivery client is down won't be able to pull blocks for chain testchainid
2017-02-06 14:29:40.835 UTC [inproccontroller] getInstance -> WARN 1b4 chaincode instance exists for vscc-1.0.0-snapshot-preview-305216ca522e84d0bf8c2b542b16bd3901dcb1879a970ae7c1eee3a74fbdee583eb8b74ad88edefc3d9647d47663f6b14574734c93a36b3968b077f3870d79cf
2017-02-06 14:29:40.838 UTC [peer] Initialize -> WARN 1e1 Failed to load ledger testchainid(Ledger already opened)

**Error I get for orderer**
panic: Failed initializing crypto [Could not load a valid ca certificate from directory /etc/hyperledger/msp/sampleconfig/cacerts, err Could not read directory open /etc/hyperledger/msp/sampleconfig/cacerts: no such file or directory, err /etc/hyperledger/msp/sampleconfig/cacerts]
2017-02-06T14:21:14.718993243Z 
goroutine 1 [running]:
panic(0xa08f00, 0xc420202740)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
/go/src/github.com/hyperledger/fabric/orderer/main.go:89 +0x16df

I am using docker for Mac.
Could you please give some insights in what I should do to fix the problem?
Thanks a lot, Kind regards Koen

**Comment by bonen** [comment]
We seem to have found a solution:

**1.Updating the fabric-orderer dockerfile**
FROM hyperledger/fabric-orderer
RUN cp -r msp /etc/hyperledger/msp

**2. Adding an extra tag for snapsho:**
docker tag hyperledger/fabric-ccenv:x86_64-1.0.0-preview hyperledger/fabric-ccenv:x86_64-1.0.0-snapshot-preview

**Comment by bonen** [comment]
hi yeasy, with the latest docker updates it's broken again (orderer & peer return a panic)!  

**fabric-orderer** | 2017-02-07 13:43:18.427 UTC [msp] getPemMaterialFromDir -> INFO 004 Reading directory /etc/hyperledger/fabric/msp/sampleconfig/cacerts
fabric-orderer | panic: Failed initializing crypto [Could not load a valid ca certificate from directory /etc/hyperledger/fabric/msp/sampleconfig/cacerts, err Could not read directory open /etc/hyperledger/fabric/msp/sampleconfig/cacerts: no such file or directory, err /etc/hyperledger/fabric/msp/sampleconfig/cacerts]
fabric-orderer |
fabric-orderer | goroutine 1 [running]:
fabric-orderer | panic(0xa08f00, 0xc420208bc0)
fabric-orderer | 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
fabric-orderer | main.main()
fabric-orderer | 	/go/src/github.com/hyperledger/fabric/orderer/main.go:89 +0x16df


**fabric-vp0** | panic: Fatal error when initializing core config : Fatal error when reading core config file: Unsupported Config Type ""
fabric-vp0 |
fabric-vp0 |
fabric-vp0 |
fabric-vp0 | goroutine 1 [running]:
fabric-vp0 | panic(0xb74300, 0xc4201c36c0)
fabric-vp0 | 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
fabric-vp0 | main.main()
fabric-vp0 | 	/go/src/github.com/hyperledger/fabric/peer/main.go:88 +0x74e
fabric-vp0 exited with code 2

**Comment by yeasy** [comment]
Yeap, the repo code is changing, I've fixed several changes, pls try later.

**Comment by bonen** [comment]
Ok Thanks for your comment! Do you have any idea how much later? (By the end of this weekend we will be participating in a blockchain hackathon and we planned to work fabric1.0)

**Comment by yeasy** [comment]
See http://hyperledger-fabric.readthedocs.io/en/latest/gettingstarted/ if u need a hurry push.

**Comment by bonen** [comment]
Thanks!
